services:
  api:
    image: api
    container_name: api
    build:
      context: .
      dockerfile: PatientManagement.Api/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - appnetwork
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-db
    environment:
      - SA_PASSWORD=Password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - appnetwork

  consoleapp:
    image: consoleapp
    container_name: console-app
    build:
      context: .
      dockerfile: PatientManagement.ConsoleApp/Dockerfile
    depends_on:
      - api
    environment:
      - API_URL=http://api/patient
    networks:
      - appnetwork

volumes:
  sqlserverdata:

networks:
  appnetwork:
    driver: bridge